"""empty message

Revision ID: afad082c441e
Revises: 
Create Date: 2021-03-21 12:36:41.232496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afad082c441e'
down_revision = None
branch_labels = None
depends_on = None
#! swapped downgrade and upgrade here


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
                    sa.Column('_id', sa.VARCHAR(length=250),
                              autoincrement=False, nullable=False),
                    sa.Column('contactid', sa.VARCHAR(length=250),
                              autoincrement=False, nullable=True),
                    sa.Column('contactstatus', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=True),
                    sa.Column('contactname', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactground', sa.VARCHAR(length=3),
                              autoincrement=False, nullable=True),
                    sa.Column('contactsatellite', sa.VARCHAR(length=7),
                              autoincrement=False, nullable=True),
                    sa.Column('contactequipment', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=True),
                    sa.Column('contactstate', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=True),
                    sa.Column('contactstep', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=True),
                    sa.Column('contactdetail', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('contactbegintimestamp', sa.BIGINT(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactendtimestamp', sa.BIGINT(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactlatitude', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactlongitude', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactazimuth', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactelevation', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('contactresolution', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=True),
                    sa.Column('contactresolutionstatus', sa.VARCHAR(
                        length=25), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('_id', name='contacts_pkey')
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    sa.UniqueConstraint('username', name='users_username_key')
                    )
    op.create_table('alerts',
                    sa.Column('errorid', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=False),
                    sa.Column('errorseverity', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=True),
                    sa.Column('errorcategory', sa.VARCHAR(length=25),
                              autoincrement=False, nullable=True),
                    sa.Column('errormessage', sa.VARCHAR(length=250),
                              autoincrement=False, nullable=True),
                    sa.Column('longmessage', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('errortime', sa.BIGINT(),
                              autoincrement=False, nullable=True),
                    sa.Column('selected', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('new', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('expanded', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('errorid', name='alerts_pkey')
                    )
    # ### end Alembic commands ###
